#ifndef _TYPE_
#define _TYPE_
#include <intrins.h>

#include "_STC8X_.h"
typedef bit BOOL;
#define BYTE unsigned char
#define WORD unsigned int
#define DWORD unsigned long
#define WCHAR unsigned int
#define UINT unsigned int

#define u8 unsigned char
#define u16 unsigned int
#define u32 unsigned long
#define int8_t signed char
#define int16_t signed int
#define int32_t signed long

#define uchar unsigned char
#define uint unsigned int
#define ushort unsigned int
#define ulong unsigned long

#define uint8_t unsigned char
#define uint16_t unsigned int
#define uint32_t unsigned long
#ifndef NULL
#define NULL ((void *)0)
#endif

#endif